// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVatTu.Data;


#nullable disable

namespace QuanLyVatTu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527181123_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyVatTu.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongTheoChungTu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SoLuongThucNhap")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapId");

                    b.HasIndex("VatTuId");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhieuXuatId")
                        .HasColumnType("int");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongThucXuat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SoLuongYeuCau")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VatTuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuXuatId");

                    b.HasIndex("VatTuId");

                    b.ToTable("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsKhóa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhanQuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhanQuyenId");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Quản trị viên",
                            IsKhóa = false,
                            MatKhau = "Admin@123",
                            PhanQuyenId = 1,
                            TenDangNhap = "admin"
                        });
                });

            modelBuilder.Entity("QuanLyVatTu.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHeThongs");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhanQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenNhomQuyen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PhanQuyens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị viên hệ thống",
                            TenNhomQuyen = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Quản lý kho",
                            TenNhomQuyen = "Quản Lý"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Nhân viên",
                            TenNhomQuyen = "Nhân Viên"
                        });
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaDiemKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeToanTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiLapId")
                        .HasColumnType("int");

                    b.Property<string>("NhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhapTaiKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoanCo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuKho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiLapId");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaDiemKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeToanTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoXuat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiLapId")
                        .HasColumnType("int");

                    b.Property<string>("NguoiMua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiNhanHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoanCo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XuatTaiKho")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiLapId");

                    b.ToTable("PhieuXuats");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.VatTu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("TonToiThieu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VatTus");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu.Models.VatTu", "VatTu")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("PhieuXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuat");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.PhanQuyen", "PhanQuyen")
                        .WithMany("NguoiDung")
                        .HasForeignKey("PhanQuyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhanQuyen");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.NguoiDung", "NguoiDung")
                        .WithMany("NhatKyHeThongs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.NguoiDung", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuXuat", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.NguoiDung", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyVatTu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.NguoiDung", b =>
                {
                    b.Navigation("NhatKyHeThongs");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("QuanLyVatTu.Models.VatTu", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
